### PR TITLE
minor version - Adds the option to deactivate the best region to align. Closes #2

### LINKED ISSUE #2: Add feature to allow force the preferred alignment position
Nowadays, `metal-position` always try auto-align the element to fit the viewport. But a developer might prefer don't follow this behaviour.

We can achieve this by adding a property `autoAlignment`, that is `true` by default. In case the developer sets it to `false` we skip the `autoAlignment`.

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Very nice. LGTM.

**Comment by fernandosouza** [comment]
Travis shows a strange error. I'm looking into it.

**Comment by fernandosouza** [comment]
I updated travis.yml and all tests have passed.

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Merged and published `2.1.0`. Nice job!

**Pull request merged**
